package com.agguy.moni.app.icons

/**
 * Material Symbols 图标分组与中文显示名定义。
 */
data class SymbolIconInfo(
    val name: String,
    val codepoint: Int,
    val displayName: String,
)

data class SymbolIconGroup(
    val label: String,
    val icons: List<SymbolIconInfo>,
)

object SymbolGroups {

    /** 饮食 */
    val 饮食 = listOf(
        SymbolIconInfo("restaurant", 0xE56C, "餐厅"),
        SymbolIconInfo("local_dining", 0xE561, "用餐"),
        SymbolIconInfo("local_cafe", 0xEB44, "咖啡馆"),
        SymbolIconInfo("local_bar", 0xE540, "酒吧"),
        SymbolIconInfo("coffee", 0xEFEF, "咖啡"),
        SymbolIconInfo("bakery_dining", 0xEA53, "烘焙"),
        SymbolIconInfo("lunch_dining", 0xEA61, "午餐"),
        SymbolIconInfo("dinner_dining", 0xEA57, "晚餐"),
        SymbolIconInfo("fastfood", 0xE57A, "快餐"),
        SymbolIconInfo("icecream", 0xEA69, "冰淇淋"),
        SymbolIconInfo("cake", 0xE7E9, "蛋糕"),
        SymbolIconInfo("wine_bar", 0xF1E8, "红酒"),
        SymbolIconInfo("local_drink", 0xE544, "饮料"),
        SymbolIconInfo("water_drop", 0xE798, "水滴"),
        SymbolIconInfo("set_meal", 0xF1EA, "套餐"),
        SymbolIconInfo("soup_kitchen", 0xE7D3, "汤"),
        SymbolIconInfo("brunch_dining", 0xEA73, "早午餐"),
        SymbolIconInfo("ramen_dining", 0xEA64, "拉面"),
        SymbolIconInfo("tapas", 0xF1E9, "小吃"),
        SymbolIconInfo("egg", 0xEACC, "鸡蛋"),
        SymbolIconInfo("egg_alt", 0xEAC8, "鸡蛋"),
        SymbolIconInfo("grocery", 0xEF97, "杂货"),
        SymbolIconInfo("kebab_dining", 0xE842, "烤肉"),
        SymbolIconInfo("outdoor_grill", 0xEA47, "烧烤"),
        SymbolIconInfo("restaurant_menu", 0xE561, "菜单"),
        SymbolIconInfo("food_bank", 0xF1F2, "食物银行"),
        SymbolIconInfo("kitchen", 0xEB47, "厨房"),
        SymbolIconInfo("blender", 0xEFE3, "搅拌机"),
        SymbolIconInfo("coffee_maker", 0xEFF0, "咖啡机"),
        SymbolIconInfo("dishwasher", 0xE9A0, "洗碗机"),
        SymbolIconInfo("microwave", 0xF204, "微波炉"),
        SymbolIconInfo("oven", 0xE9C7, "烤箱"),
        SymbolIconInfo("cooking", 0xE2B6, "烹饪"),
        SymbolIconInfo("multicooker", 0xE293, "多功能锅"),
    )

    /** 交通出行 */
    val 交通出行 = listOf(
        SymbolIconInfo("directions_car", 0xEFF7, "汽车"),
        SymbolIconInfo("directions_bus", 0xEFF6, "公交"),
        SymbolIconInfo("train", 0xE570, "火车"),
        SymbolIconInfo("flight", 0xE539, "飞机"),
        SymbolIconInfo("directions_bike", 0xE52F, "自行车"),
        SymbolIconInfo("directions_boat", 0xEFF5, "船"),
        SymbolIconInfo("local_taxi", 0xE559, "出租车"),
        SymbolIconInfo("tram", 0xE571, "电车"),
        SymbolIconInfo("subway", 0xE56F, "地铁"),
        SymbolIconInfo("directions_walk", 0xE536, "步行"),
        SymbolIconInfo("local_shipping", 0xE558, "货运"),
        SymbolIconInfo("electric_car", 0xEB1C, "电动车"),
        SymbolIconInfo("electric_bike", 0xEB1B, "电动自行车"),
        SymbolIconInfo("electric_moped", 0xEB1D, "电动轻摩"),
        SymbolIconInfo("electric_rickshaw", 0xEB1E, "电动三轮"),
        SymbolIconInfo("electric_scooter", 0xEB1F, "电动滑板车"),
        SymbolIconInfo("flight_takeoff", 0xE905, "起飞"),
        SymbolIconInfo("flight_land", 0xE904, "降落"),
        SymbolIconInfo("local_airport", 0xE53D, "机场"),
        SymbolIconInfo("hail", 0xE9B1, "打车"),
        SymbolIconInfo("two_wheeler", 0xE9F9, "两轮车"),
        SymbolIconInfo("rv_hookup", 0xE642, "房车挂钩"),
        SymbolIconInfo("snowmobile", 0xE503, "雪地摩托"),
        SymbolIconInfo("sailing", 0xE502, "帆船"),
        SymbolIconInfo("motorcycle", 0xE91B, "摩托"),
        SymbolIconInfo("local_gas_station", 0xE546, "加油站"),
        SymbolIconInfo("local_parking", 0xE54F, "停车"),
        SymbolIconInfo("traffic", 0xE565, "交通"),
        SymbolIconInfo("tire_repair", 0xEBC8, "轮胎维修"),
        SymbolIconInfo("taxi_alert", 0xEF74, "出租车警报"),
    )

    /** 购物消费 */
    val 购物消费 = listOf(
        SymbolIconInfo("shopping_bag", 0xF1CC, "购物袋"),
        SymbolIconInfo("shopping_cart", 0xE8CC, "购物车"),
        SymbolIconInfo("storefront", 0xEA12, "店铺"),
        SymbolIconInfo("local_mall", 0xE54C, "商场"),
        SymbolIconInfo("redeem", 0xE8F6, "兑换"),
        SymbolIconInfo("sell", 0xF05B, "出售"),
        SymbolIconInfo("payments", 0xEF63, "支付"),
        SymbolIconInfo("credit_card", 0xE8A1, "信用卡"),
        SymbolIconInfo("account_balance", 0xE84F, "账户余额"),
        SymbolIconInfo("account_balance_wallet", 0xE850, "钱包余额"),
        SymbolIconInfo("wallet", 0xF8FF, "钱包"),
        SymbolIconInfo("savings", 0xE2EB, "储蓄"),
        SymbolIconInfo("paid", 0xF041, "已付"),
        SymbolIconInfo("money", 0xE57D, "钱币"),
        SymbolIconInfo("attach_money", 0xE227, "货币"),
        SymbolIconInfo("price_check", 0xF04B, "价格核对"),
        SymbolIconInfo("price_change", 0xF04A, "价格变动"),
        SymbolIconInfo("receipt_long", 0xEF6E, "长收据"),
        SymbolIconInfo("receipt", 0xE8B0, "收据"),
        SymbolIconInfo("barcode_scanner", 0xE70C, "条码扫描"),
        SymbolIconInfo("local_offer", 0xF05B, "优惠"),
        SymbolIconInfo("shoppingmode", 0xEFB7, "购物模式"),
        SymbolIconInfo("store", 0xE8D1, "商店"),
    )

    /** 家居生活 */
    val 家居生活 = listOf(
        SymbolIconInfo("home", 0xE9B2, "首页"),
        SymbolIconInfo("chair", 0xEFED, "椅子"),
        SymbolIconInfo("bed", 0xEFDF, "床"),
        SymbolIconInfo("cleaning_services", 0xF0FF, "清洁服务"),
        SymbolIconInfo("kitchen", 0xEB47, "厨房"),
        SymbolIconInfo("local_laundry_service", 0xE54A, "洗衣服务"),
        SymbolIconInfo("water_drop", 0xE798, "水滴"),
        SymbolIconInfo("lightbulb", 0xE90F, "灯泡"),
        SymbolIconInfo("door_front", 0xEFFD, "前门"),
        SymbolIconInfo("yard", 0xF089, "庭院"),
        SymbolIconInfo("bathroom", 0xEFDD, "浴室"),
        SymbolIconInfo("bathtub", 0xEA41, "浴缸"),
        SymbolIconInfo("dry_cleaning", 0xEA58, "干洗"),
        SymbolIconInfo("garage", 0xF011, "车库"),
        SymbolIconInfo("grass", 0xF205, "草坪"),
        SymbolIconInfo("house", 0xEA44, "房屋"),
        SymbolIconInfo("houseboat", 0xE584, "船屋"),
        SymbolIconInfo("meeting_room", 0xEB4F, "会议室"),
        SymbolIconInfo("warehouse", 0xEBB8, "仓库"),
        SymbolIconInfo("ac_unit", 0xEB3B, "空调"),
        SymbolIconInfo("air_purifier", 0xE97E, "空气净化器"),
        SymbolIconInfo("air_purifier_gen", 0xE829, "净化器二代"),
        SymbolIconInfo("mode_fan", 0xF168, "风扇"),
        SymbolIconInfo("fireplace", 0xEA43, "壁炉"),
        SymbolIconInfo("foundation", 0xF200, "地基"),
        SymbolIconInfo("roofing", 0xF201, "屋顶"),
        SymbolIconInfo("tv", 0xE63B, "电视"),
        SymbolIconInfo("bedroom_baby", 0xEFE0, "婴儿房"),
        SymbolIconInfo("bedroom_child", 0xEFE1, "儿童房"),
        SymbolIconInfo("bedroom_parent", 0xEFE2, "主卧"),
    )

    /** 工作办公 */
    val 工作办公 = listOf(
        SymbolIconInfo("work", 0xE943, "工作"),
        SymbolIconInfo("computer", 0xE31E, "电脑"),
        SymbolIconInfo("business_center", 0xEB3F, "商务中心"),
        SymbolIconInfo("build", 0xF8CD, "建造"),
        SymbolIconInfo("cloud", 0xF15C, "云"),
        SymbolIconInfo("wifi", 0xE63E, "无线网"),
        SymbolIconInfo("request_quote", 0xF1B6, "报价请求"),
        SymbolIconInfo("trending_up", 0xE8E5, "上升趋势"),
        SymbolIconInfo("engineering", 0xEA3D, "工程"),
        SymbolIconInfo("corporate_fare", 0xF1D0, "企业费用"),
        SymbolIconInfo("desk", 0xF8F4, "办公桌"),
        SymbolIconInfo("draft", 0xE66D, "草稿"),
        SymbolIconInfo("fax", 0xEAD8, "传真"),
        SymbolIconInfo("inventory", 0xE179, "库存"),
        SymbolIconInfo("label", 0xE893, "标签"),
        SymbolIconInfo("mail", 0xE159, "邮件"),
        SymbolIconInfo("mark_email_read", 0xF18C, "邮件已读"),
        SymbolIconInfo("move_to_inbox", 0xE168, "移至收件箱"),
        SymbolIconInfo("outbox", 0xEF5F, "发件箱"),
        SymbolIconInfo("send", 0xE163, "发送"),
        SymbolIconInfo("co_present", 0xEAF0, "共同演示"),
        SymbolIconInfo("contact_mail", 0xE0D0, "联系邮件"),
        SymbolIconInfo("contact_phone", 0xF0C0, "联系电话"),
        SymbolIconInfo("description", 0xE873, "描述"),
        SymbolIconInfo("feed", 0xF009, "动态"),
        SymbolIconInfo("find_in_page", 0xE880, "页面查找"),
        SymbolIconInfo("forward_to_inbox", 0xF187, "转发到收件箱"),
        SymbolIconInfo("handshake", 0xEBCB, "握手"),
        SymbolIconInfo("note_add", 0xE89C, "添加笔记"),
        SymbolIconInfo("post_add", 0xEA20, "添加帖子"),
        SymbolIconInfo("publish", 0xE255, "发布"),
    )

    /** 医疗健康 */
    val 医疗健康 = listOf(
        SymbolIconInfo("local_hospital", 0xE548, "医院"),
        SymbolIconInfo("medication", 0xF033, "药物"),
        SymbolIconInfo("fitness_center", 0xEB43, "健身中心"),
        SymbolIconInfo("health_and_safety", 0xE1D5, "健康安全"),
        SymbolIconInfo("vaccines", 0xE138, "疫苗"),
        SymbolIconInfo("healing", 0xE3F3, "治疗"),
        SymbolIconInfo("psychology", 0xEA4A, "心理"),
        SymbolIconInfo("spa", 0xEB4C, "水疗"),
        SymbolIconInfo("bloodtype", 0xEFE4, "血型"),
        SymbolIconInfo("emergency", 0xE1EB, "急救"),
        SymbolIconInfo("medical_services", 0xF109, "医疗服务"),
        SymbolIconInfo("pill", 0xE11F, "药丸"),
        SymbolIconInfo("biotech", 0xEA3A, "生物技术"),
        SymbolIconInfo("science", 0xEA4B, "科学"),
        SymbolIconInfo("clean_hands", 0xF21F, "洗手"),
        SymbolIconInfo("health_and_beauty", 0xEF9D, "健康美容"),
        SymbolIconInfo("coronavirus", 0xF221, "病毒"),
        SymbolIconInfo("masks", 0xF218, "口罩"),
        SymbolIconInfo("sick", 0xF220, "生病"),
        SymbolIconInfo("thermometer", 0xE846, "体温计"),
        SymbolIconInfo("medical_information", 0xEBED, "医疗信息"),
        SymbolIconInfo("personal_injury", 0xE6DA, "人身伤害"),
        SymbolIconInfo("severe_cold", 0xEBD3, "重感冒"),
        SymbolIconInfo("stethoscope", 0xF805, "听诊器"),
        SymbolIconInfo("surgical", 0xE131, "外科"),
        SymbolIconInfo("ward", 0xE13C, "病房"),
    )

    /** 教育学习 */
    val 教育学习 = listOf(
        SymbolIconInfo("school", 0xE80C, "学校"),
        SymbolIconInfo("book", 0xE86E, "书籍"),
        SymbolIconInfo("local_library", 0xE54B, "图书馆"),
        SymbolIconInfo("menu_book", 0xEA19, "菜单书"),
        SymbolIconInfo("science", 0xEA4B, "科学"),
        SymbolIconInfo("calculate", 0xEA5F, "计算"),
        SymbolIconInfo("edit_note", 0xE745, "编辑笔记"),
        SymbolIconInfo("auto_stories", 0xE666, "故事"),
        SymbolIconInfo("cast_for_education", 0xEFEC, "教育投屏"),
        SymbolIconInfo("draw", 0xE746, "绘画"),
        SymbolIconInfo("edit_document", 0xF88C, "编辑文档"),
        SymbolIconInfo("explore", 0xE87A, "探索"),
        SymbolIconInfo("history_edu", 0xEA3E, "历史教育"),
        SymbolIconInfo("palette", 0xE40A, "调色板"),
        SymbolIconInfo("quiz", 0xF04C, "测验"),
        SymbolIconInfo("self_improvement", 0xEA78, "自我提升"),
        SymbolIconInfo("sort_by_alpha", 0xE053, "按字母排序"),
        SymbolIconInfo("translate", 0xE8E2, "翻译"),
        SymbolIconInfo("architecture", 0xEA3B, "建筑"),
        SymbolIconInfo("brush", 0xE3AE, "画笔"),
        SymbolIconInfo("code", 0xE86F, "代码"),
        SymbolIconInfo("data_object", 0xEAD3, "数据对象"),
        SymbolIconInfo("design_services", 0xF10A, "设计服务"),
        SymbolIconInfo("developer_board", 0xE30D, "开发板"),
        SymbolIconInfo("developer_mode", 0xF2E2, "开发者模式"),
        SymbolIconInfo("diamond", 0xEAD5, "钻石"),
        SymbolIconInfo("functions", 0xE24A, "函数"),
        SymbolIconInfo("insights", 0xF092, "洞察"),
        SymbolIconInfo("model_training", 0xF0CF, "模型训练"),
        SymbolIconInfo("modeling", 0xF3AA, "建模"),
        SymbolIconInfo("numbers", 0xEAC7, "数字"),
        SymbolIconInfo("square_foot", 0xEA49, "平方英尺"),
    )

    /** 娱乐休闲 */
    val 娱乐休闲 = listOf(
        SymbolIconInfo("sports_esports", 0xEA28, "电竞"),
        SymbolIconInfo("movie", 0xE404, "电影"),
        SymbolIconInfo("music_note", 0xE405, "音乐"),
        SymbolIconInfo("travel_explore", 0xE2DB, "旅行探索"),
        SymbolIconInfo("sports_basketball", 0xEA26, "篮球"),
        SymbolIconInfo("sports_soccer", 0xEA2F, "足球"),
        SymbolIconInfo("pool", 0xEB48, "台球"),
        SymbolIconInfo("casino", 0xEB40, "娱乐场"),
        SymbolIconInfo("theater_comedy", 0xEA66, "喜剧"),
        SymbolIconInfo("festival", 0xEA68, "节日"),
        SymbolIconInfo("camera", 0xE3AF, "相机"),
        SymbolIconInfo("games", 0xE30F, "游戏"),
        SymbolIconInfo("headset", 0xF01F, "耳机"),
        SymbolIconInfo("adaptive_audio_mic", 0xF4CC, "麦克风"),
        SymbolIconInfo("piano", 0xE521, "钢琴"),
        SymbolIconInfo("skateboarding", 0xE511, "滑板"),
        SymbolIconInfo("snowboarding", 0xE513, "滑雪板"),
        SymbolIconInfo("toys", 0xE332, "玩具"),
        SymbolIconInfo("playground", 0xF28E, "游乐场"),
        SymbolIconInfo("playground_2", 0xF28F, "游乐场2"),
        SymbolIconInfo("smart_toy", 0xF06C, "智能玩具"),
        SymbolIconInfo("sports_baseball", 0xEA51, "棒球"),
        SymbolIconInfo("sports_football", 0xEA29, "橄榄球"),
        SymbolIconInfo("sports_golf", 0xEA2A, "高尔夫"),
        SymbolIconInfo("sports_hockey", 0xEA2B, "冰球"),
        SymbolIconInfo("sports_mma", 0xEA2C, "格斗"),
        SymbolIconInfo("sports_rugby", 0xEA2E, "橄榄球"),
        SymbolIconInfo("sports_tennis", 0xEA32, "网球"),
        SymbolIconInfo("sports_volleyball", 0xEA31, "排球"),
        SymbolIconInfo("surfing", 0xE515, "冲浪"),
        SymbolIconInfo("sports_handball", 0xEA33, "手球"),
    )

    /** 人物社交 */
    val 人物社交 = listOf(
        SymbolIconInfo("person", 0xF0D3, "个人"),
        SymbolIconInfo("people", 0xEA21, "人群"),
        SymbolIconInfo("group", 0xEA21, "群组"),
        SymbolIconInfo("family_restroom", 0xF1A2, "家庭卫生间"),
        SymbolIconInfo("child_care", 0xEB41, "育儿"),
        SymbolIconInfo("diversity_1", 0xF8D7, "多元1"),
        SymbolIconInfo("diversity_2", 0xF8D8, "多元2"),
        SymbolIconInfo("diversity_3", 0xF8D9, "多元3"),
        SymbolIconInfo("handshake", 0xEBCB, "握手"),
        SymbolIconInfo("sentiment_satisfied", 0xE813, "满意"),
        SymbolIconInfo("sentiment_dissatisfied", 0xE811, "不满"),
        SymbolIconInfo("thumb_up", 0xF577, "点赞"),
        SymbolIconInfo("thumb_down", 0xF578, "点踩"),
        SymbolIconInfo("favorite", 0xE87E, "收藏"),
        SymbolIconInfo("heart_broken", 0xEAC2, "心碎"),
        SymbolIconInfo("mood", 0xEA22, "心情"),
        SymbolIconInfo("mood_bad", 0xE7F3, "心情差"),
        SymbolIconInfo("self_improvement", 0xEA78, "自我提升"),
        SymbolIconInfo("support_agent", 0xF0E2, "客服"),
        SymbolIconInfo("volunteer_activism", 0xEA70, "志愿公益"),
        SymbolIconInfo("workspace_premium", 0xE7AF, "高级工作区"),
        SymbolIconInfo("workspaces", 0xEA0F, "工作空间"),
        SymbolIconInfo("celebration", 0xEA65, "庆祝"),
        SymbolIconInfo("event", 0xE878, "活动"),
        SymbolIconInfo("flutter_dash", 0xE00B, "Flutter"),
        SymbolIconInfo("group_add", 0xE7F0, "添加群组"),
        SymbolIconInfo("groups", 0xF233, "群组"),
        SymbolIconInfo("groups_2", 0xF8DF, "群组2"),
        SymbolIconInfo("groups_3", 0xF8E0, "群组3"),
        SymbolIconInfo("interpreter_mode", 0xE83B, "翻译模式"),
    )

    /** 自然户外 */
    val 自然户外 = listOf(
        SymbolIconInfo("park", 0xEA63, "公园"),
        SymbolIconInfo("nature", 0xE406, "自然"),
        SymbolIconInfo("nature_people", 0xE407, "自然人物"),
        SymbolIconInfo("landscape", 0xE564, "风景"),
        SymbolIconInfo("beach_access", 0xEB3E, "海滩"),
        SymbolIconInfo("camping", 0xF8A2, "露营"),
        SymbolIconInfo("downhill_skiing", 0xE509, "高山滑雪"),
        SymbolIconInfo("hiking", 0xE50A, "徒步"),
        SymbolIconInfo("kayaking", 0xE50C, "皮划艇"),
        SymbolIconInfo("kitesurfing", 0xE50D, "风筝冲浪"),
        SymbolIconInfo("nordic_walking", 0xE50E, "北欧步行"),
        SymbolIconInfo("paragliding", 0xE50F, "滑翔伞"),
        SymbolIconInfo("rowing", 0xE921, "划船"),
        SymbolIconInfo("scuba_diving", 0xEBCE, "水肺潜水"),
        SymbolIconInfo("ice_skating", 0xE50B, "滑冰"),
        SymbolIconInfo("roller_skating", 0xEBCD, "轮滑"),
        SymbolIconInfo("terrain", 0xE564, "地形"),
        SymbolIconInfo("waves", 0xE176, "波浪"),
        SymbolIconInfo("agriculture", 0xEA79, "农业"),
        SymbolIconInfo("compost", 0xE761, "堆肥"),
        SymbolIconInfo("eco", 0xEA35, "生态"),
        SymbolIconInfo("cyclone", 0xEBD5, "旋风"),
        SymbolIconInfo("flood", 0xEBE6, "洪水"),
        SymbolIconInfo("tsunami", 0xEBD8, "海啸"),
        SymbolIconInfo("tornado", 0xE199, "龙卷风"),
        SymbolIconInfo("thunderstorm", 0xEBDB, "雷暴"),
        SymbolIconInfo("sunny", 0xE81A, "晴天"),
        SymbolIconInfo("ac_unit", 0xEB3B, "空调"),
        SymbolIconInfo("thermostat", 0xF076, "恒温器"),
        SymbolIconInfo("tsunami", 0xEBD8, "海啸"),
    )

    /** 科技数码 */
    val 科技数码 = listOf(
        SymbolIconInfo("smartphone", 0xE7BA, "手机"),
        SymbolIconInfo("laptop", 0xE31E, "笔记本"),
        SymbolIconInfo("tablet", 0xE32F, "平板"),
        SymbolIconInfo("watch", 0xE334, "手表"),
        SymbolIconInfo("tv", 0xE63B, "电视"),
        SymbolIconInfo("speaker", 0xE32D, "音箱"),
        SymbolIconInfo("headphones", 0xF01F, "耳机"),
        SymbolIconInfo("camera", 0xE3AF, "相机"),
        SymbolIconInfo("videocam", 0xE04B, "摄像"),
        SymbolIconInfo("bluetooth", 0xE1A7, "蓝牙"),
        SymbolIconInfo("gps_fixed", 0xE55C, "定位"),
        SymbolIconInfo("network_cell", 0xE1B9, "蜂窝网络"),
        SymbolIconInfo("network_wifi", 0xE1BA, "WiFi"),
        SymbolIconInfo("sd_card", 0xE623, "SD卡"),
        SymbolIconInfo("sim_card", 0xE32B, "SIM卡"),
        SymbolIconInfo("storage", 0xE1DB, "存储"),
        SymbolIconInfo("usb", 0xE1E0, "USB"),
        SymbolIconInfo("battery_full", 0xE1A5, "满电"),
        SymbolIconInfo("charging_station", 0xF2E3, "充电站"),
        SymbolIconInfo("power", 0xE63C, "电源"),
        SymbolIconInfo("desktop_mac", 0xE30B, "Mac"),
        SymbolIconInfo("desktop_windows", 0xE30C, "Windows"),
        SymbolIconInfo("device_hub", 0xE335, "设备中心"),
        SymbolIconInfo("device_thermostat", 0xE1FF, "设备恒温器"),
        SymbolIconInfo("devices", 0xE326, "设备"),
        SymbolIconInfo("devices_fold", 0xEBDE, "折叠设备"),
        SymbolIconInfo("display_settings", 0xEB97, "显示设置"),
        SymbolIconInfo("dvr", 0xE1B2, "录像"),
        SymbolIconInfo("earbuds", 0xF003, "耳塞"),
        SymbolIconInfo("earbuds_battery", 0xF004, "耳塞电池"),
        SymbolIconInfo("headset_mic", 0xE311, "耳麦"),
    )

    /** 其他 */
    val 其他 = listOf(
        SymbolIconInfo("more_horiz", 0xE5D3, "更多"),
        SymbolIconInfo("star", 0xF09A, "星星"),
        SymbolIconInfo("pets", 0xE91D, "宠物"),
        SymbolIconInfo("gavel", 0xE90E, "法槌"),
        SymbolIconInfo("security", 0xE32A, "安全"),
        SymbolIconInfo("info", 0xE88E, "信息"),
        SymbolIconInfo("help", 0xE8FD, "帮助"),
        SymbolIconInfo("tune", 0xE429, "调节"),
        SymbolIconInfo("palette", 0xE40A, "调色板"),
        SymbolIconInfo("archive", 0xE149, "归档"),
        SymbolIconInfo("unarchive", 0xE169, "恢复"),
        SymbolIconInfo("expand_more", 0xE5CF, "展开"),
        SymbolIconInfo("expand_less", 0xE5CE, "收起"),
        SymbolIconInfo("category", 0xE574, "分类"),
        SymbolIconInfo("bookmark", 0xE8E7, "书签"),
        SymbolIconInfo("flag", 0xF0C6, "旗帜"),
        SymbolIconInfo("label", 0xE893, "标签"),
        SymbolIconInfo("lock", 0xE899, "锁"),
        SymbolIconInfo("key", 0xE73C, "钥匙"),
        SymbolIconInfo("verified", 0xEF76, "已验证"),
        SymbolIconInfo("add", 0xE145, "添加"),
        SymbolIconInfo("check", 0xE5CA, "勾选"),
        SymbolIconInfo("close", 0xE5CD, "关闭"),
        SymbolIconInfo("delete", 0xE92E, "删除"),
        SymbolIconInfo("edit", 0xF097, "编辑"),
        SymbolIconInfo("arrow_back", 0xE5C4, "返回"),
        SymbolIconInfo("arrow_forward", 0xE5C8, "前进"),
        SymbolIconInfo("menu", 0xE5D2, "菜单"),
        SymbolIconInfo("more_vert", 0xE5D4, "更多"),
        SymbolIconInfo("settings", 0xE8B8, "设置"),
        SymbolIconInfo("search", 0xE8B6, "搜索"),
        SymbolIconInfo("filter_list", 0xE152, "筛选"),
        SymbolIconInfo("sort", 0xE164, "排序"),
        SymbolIconInfo("refresh", 0xE5D5, "刷新"),
        SymbolIconInfo("home", 0xE9B2, "首页"),
        SymbolIconInfo("person", 0xF0D3, "个人"),
        SymbolIconInfo("notifications", 0xE7F5, "通知"),
        SymbolIconInfo("share", 0xE80D, "分享"),
        SymbolIconInfo("download", 0xF090, "下载"),
        SymbolIconInfo("upload", 0xF09B, "上传"),
        SymbolIconInfo("print", 0xE8AD, "打印"),
        SymbolIconInfo("calendar_today", 0xE935, "日历"),
        SymbolIconInfo("schedule", 0xEFD6, "日程"),
        SymbolIconInfo("location_on", 0xF1DB, "位置"),
        SymbolIconInfo("public", 0xE80B, "公共"),
        SymbolIconInfo("language", 0xE894, "语言"),
        SymbolIconInfo("dark_mode", 0xE51C, "深色模式"),
        SymbolIconInfo("light_mode", 0xE518, "浅色模式"),
    )

    val ALL_GROUPS = listOf(
        SymbolIconGroup("饮食", 饮食),
        SymbolIconGroup("交通出行", 交通出行),
        SymbolIconGroup("购物消费", 购物消费),
        SymbolIconGroup("家居生活", 家居生活),
        SymbolIconGroup("工作办公", 工作办公),
        SymbolIconGroup("医疗健康", 医疗健康),
        SymbolIconGroup("教育学习", 教育学习),
        SymbolIconGroup("娱乐休闲", 娱乐休闲),
        SymbolIconGroup("人物社交", 人物社交),
        SymbolIconGroup("自然户外", 自然户外),
        SymbolIconGroup("科技数码", 科技数码),
        SymbolIconGroup("其他", 其他),
    )

    val ALL_ICONS = ALL_GROUPS.flatMap { it.icons }

    /**
     * 按分类名称关键词匹配推荐图标名。
     * 返回图标名称字符串（供数据库存储）。
     */
    fun iconForCategory(name: String): String {
        val lower = name.lowercase()
        return when {
            lower.contains("餐") || lower.contains("食") || lower.contains("吃") ||
                lower.contains("饭") || lower.contains("饮") -> "restaurant"
            lower.contains("车") || lower.contains("交") || lower.contains("行") ||
                lower.contains("路") -> "directions_car"
            lower.contains("购") || lower.contains("买") || lower.contains("消费") ||
                lower.contains("物") -> "shopping_bag"
            lower.contains("家") || lower.contains("居") || lower.contains("住") -> "home"
            lower.contains("工") || lower.contains("办") || lower.contains("职") -> "work"
            lower.contains("医") || lower.contains("药") || lower.contains("健") -> "local_hospital"
            lower.contains("学") || lower.contains("教") || lower.contains("书") -> "school"
            lower.contains("游") || lower.contains("玩") || lower.contains("娱") -> "movie"
            lower.contains("人") || lower.contains("社") || lower.contains("友") -> "person"
            else -> "more_horiz"
        }
    }
}
