package com.agguy.moni.app.icons

/**
 * Material Symbols 图标名称到 Unicode codepoint 的映射。
 *
 * 数据来自 Google 官方 Material Symbols codepoints 文件。
 * 若名称找不到，fallback 到 "more_horiz"（避免显示空白方框）。
 */
object SymbolCodepoints {

    private val FALLBACK = "more_horiz"

    private val codepoints = mapOf(
        "ac_unit" to 0xEB3B, // 空调
        "account_balance" to 0xE84F, // 银行账户
        "account_balance_wallet" to 0xE850, // 账户钱包
        "account_tree" to 0xE97A, // 账户树
        "adaptive_audio_mic" to 0xF4CC, // 麦克风
        "add" to 0xE145, // 添加
        "add_photo_alternate" to 0xE43E, // 添加图片
        "agriculture" to 0xEA79, // 农业
        "air_purifier" to 0xE97E, // 空气净化器
        "air_purifier_gen" to 0xE829, // 净化器二代
        "analytics" to 0xEF3E, // 数据分析
        "architecture" to 0xEA3B, // 建筑
        "archive" to 0xE149, // 归档
        "arrow_back" to 0xE5C4, // 返回
        "arrow_forward" to 0xE5C8, // 前进
        "attach_money" to 0xE227, // 货币
        "auto_awesome" to 0xE65F, // AI 自动
        "auto_stories" to 0xE666, // 故事
        "automation" to 0xF421, // 自动化
        "bakery_dining" to 0xEA53, // 烘焙
        "bar_chart" to 0xE26B, // 柱状图
        "barcode_scanner" to 0xE70C, // 条码扫描
        "bathroom" to 0xEFDD, // 浴室
        "bathtub" to 0xEA41, // 浴缸
        "battery_full" to 0xE1A5, // 满电
        "beach_access" to 0xEB3E, // 海滩
        "bed" to 0xEFDF, // 床
        "bedroom_baby" to 0xEFE0, // 婴儿房
        "bedroom_child" to 0xEFE1, // 儿童房
        "bedroom_parent" to 0xEFE2, // 主卧
        "biotech" to 0xEA3A, // 生物技术
        "blender" to 0xEFE3, // 搅拌机
        "bloodtype" to 0xEFE4, // 血型
        "bluetooth" to 0xE1A7, // 蓝牙
        "book" to 0xE86E, // 书籍
        "bookmark" to 0xE8E7, // 书签
        "brunch_dining" to 0xEA73, // 早午餐
        "brush" to 0xE3AE, // 画笔
        "build" to 0xF8CD, // 建造
        "business_center" to 0xEB3F, // 商务中心
        "cake" to 0xE7E9, // 蛋糕
        "calculate" to 0xEA5F, // 计算
        "calendar_today" to 0xE935, // 日历
        "camera" to 0xE3AF, // 相机
        "camping" to 0xF8A2, // 露营
        "casino" to 0xEB40, // 娱乐场
        "cast_for_education" to 0xEFEC, // 教育投屏
        "category" to 0xE574, // 分类
        "celebration" to 0xEA65, // 庆祝
        "chair" to 0xEFED, // 椅子
        "charging_station" to 0xF2E3, // 充电站
        "check" to 0xE5CA, // 勾选
        "child_care" to 0xEB41, // 育儿
        "clean_hands" to 0xF21F, // 洗手
        "cleaning_services" to 0xF0FF, // 清洁服务
        "close" to 0xE5CD, // 关闭
        "cloud" to 0xF15C, // 云
        "cloud_download" to 0xE2C0, // 云下载
        "cloud_upload" to 0xE2C3, // 云上传
        "co_present" to 0xEAF0, // 共同演示
        "code" to 0xE86F, // 代码
        "coffee" to 0xEFEF, // 咖啡
        "coffee_maker" to 0xEFF0, // 咖啡机
        "compost" to 0xE761, // 堆肥
        "computer" to 0xE31E, // 电脑
        "contact_mail" to 0xE0D0, // 联系邮件
        "contact_phone" to 0xF0C0, // 联系电话
        "content_paste" to 0xE14F, // 粘贴
        "cooking" to 0xE2B6, // 烹饪
        "coronavirus" to 0xF221, // 病毒
        "corporate_fare" to 0xF1D0, // 商务差旅
        "credit_card" to 0xE8A1, // 信用卡
        "credit_score" to 0xEFF1, // 信用管理
        "currency_exchange" to 0xEB70, // 货币兑换
        "currency_yuan" to 0xEAF9, // 人民币
        "cyclone" to 0xEBD5, // 旋风
        "dark_mode" to 0xE51C, // 深色模式
        "data_object" to 0xEAD3, // 数据对象
        "data_usage" to 0xEFF2, // 数据用量
        "database" to 0xF20E, // 数据库
        "delete" to 0xE92E, // 删除
        "description" to 0xE873, // 描述
        "design_services" to 0xF10A, // 设计服务
        "desk" to 0xF8F4, // 办公桌
        "desktop_mac" to 0xE30B, // Mac
        "desktop_windows" to 0xE30C, // Windows
        "developer_board" to 0xE30D, // 开发板
        "developer_mode" to 0xF2E2, // 开发者模式
        "device_hub" to 0xE335, // 设备中心
        "device_thermostat" to 0xE1FF, // 设备恒温器
        "devices" to 0xE326, // 设备
        "devices_fold" to 0xEBDE, // 折叠设备
        "diamond" to 0xEAD5, // 钻石
        "dinner_dining" to 0xEA57, // 晚餐
        "directions_bike" to 0xE52F, // 自行车
        "directions_boat" to 0xEFF5, // 船
        "directions_bus" to 0xEFF6, // 公交
        "directions_car" to 0xEFF7, // 汽车
        "directions_walk" to 0xE536, // 步行
        "dishwasher" to 0xE9A0, // 洗碗机
        "display_settings" to 0xEB97, // 显示设置
        "diversity_1" to 0xF8D7, // 多元人群
        "diversity_2" to 0xF8D8, // 多元社群
        "diversity_3" to 0xF8D9, // 多元包容
        "domain_verification" to 0xEF4C, // 域验证
        "door_front" to 0xEFFD, // 前门
        "downhill_skiing" to 0xE509, // 高山滑雪
        "download" to 0xF090, // 下载
        "draft" to 0xE66D, // 草稿
        "draw" to 0xE746, // 绘画
        "dry_cleaning" to 0xEA58, // 干洗
        "dvr" to 0xE1B2, // 录像
        "earbuds" to 0xF003, // 耳塞
        "earbuds_battery" to 0xF004, // 耳塞电池
        "eco" to 0xEA35, // 生态
        "edit" to 0xF097, // 编辑
        "edit_document" to 0xF88C, // 编辑文档
        "edit_note" to 0xE745, // 编辑笔记
        "egg" to 0xEACC, // 鸡蛋
        "egg_alt" to 0xEAC8,
        "electric_bike" to 0xEB1B, // 电动自行车
        "electric_car" to 0xEB1C, // 电动车
        "electric_moped" to 0xEB1D, // 电动轻摩
        "electric_rickshaw" to 0xEB1E, // 电动三轮
        "electric_scooter" to 0xEB1F, // 电动滑板车
        "emergency" to 0xE1EB, // 急救
        "engineering" to 0xEA3D, // 工程
        "event" to 0xE878, // 活动
        "event_repeat" to 0xEB7B, // 周期事件
        "expand_less" to 0xE5CE, // 收起
        "expand_more" to 0xE5CF, // 展开
        "explore" to 0xE87A, // 探索
        "fact_check" to 0xF0C5, // 对账核查
        "family_restroom" to 0xF1A2, // 家庭卫生间
        "fastfood" to 0xE57A, // 快餐
        "favorite" to 0xE87E, // 收藏
        "fax" to 0xEAD8, // 传真
        "feed" to 0xF009, // 动态
        "festival" to 0xEA68, // 节日
        "filter_list" to 0xE152, // 筛选
        "find_in_page" to 0xE880, // 页面查找
        "fireplace" to 0xEA43, // 壁炉
        "fitness_center" to 0xEB43, // 健身中心
        "flag" to 0xF0C6, // 旗帜
        "flight" to 0xE539, // 飞机
        "flight_land" to 0xE904, // 降落
        "flight_takeoff" to 0xE905, // 起飞
        "flood" to 0xEBE6, // 洪水
        "flutter_dash" to 0xE00B,
        "folder_copy" to 0xEBBD, // 复制文件夹
        "folder_open" to 0xE2C8, // 打开文件夹
        "food_bank" to 0xF1F2, // 食物银行
        "forward_to_inbox" to 0xF187, // 转发到收件箱
        "foundation" to 0xF200, // 地基
        "functions" to 0xE24A, // 函数
        "games" to 0xE30F, // 游戏
        "garage" to 0xF011, // 车库
        "gavel" to 0xE90E, // 法槌
        "gps_fixed" to 0xE55C, // 定位
        "grass" to 0xF205, // 草坪
        "grocery" to 0xEF97, // 杂货
        "group" to 0xEA21,
        "group_add" to 0xE7F0, // 添加群组
        "groups" to 0xF233, // 群组
        "groups_2" to 0xF8DF, // 群组2
        "groups_3" to 0xF8E0, // 群组3
        "hail" to 0xE9B1, // 打车
        "handshake" to 0xEBCB, // 握手
        "headphones" to 0xF01F,
        "headset" to 0xF01F, // 耳机
        "headset_mic" to 0xE311, // 耳麦
        "healing" to 0xE3F3, // 治疗
        "health_and_beauty" to 0xEF9D, // 健康美容
        "health_and_safety" to 0xE1D5, // 健康安全
        "heart_broken" to 0xEAC2, // 心碎
        "help" to 0xE8FD, // 帮助
        "hiking" to 0xE50A, // 徒步
        "history_edu" to 0xEA3E, // 历史教育
        "home" to 0xE9B2, // 首页
        "house" to 0xEA44, // 房屋
        "houseboat" to 0xE584, // 船屋
        "ice_skating" to 0xE50B, // 滑冰
        "icecream" to 0xEA69, // 冰淇淋
        "image" to 0xE3F4, // 图片
        "info" to 0xE88E, // 信息
        "insights" to 0xF092, // 智能洞察
        "interpreter_mode" to 0xE83B, // 翻译模式
        "inventory" to 0xE179, // 库存
        "kayaking" to 0xE50C, // 皮划艇
        "kebab_dining" to 0xE842, // 烤肉
        "key" to 0xE73C, // 钥匙
        "kitchen" to 0xEB47, // 厨房
        "kitesurfing" to 0xE50D, // 风筝冲浪
        "label" to 0xE893, // 标签
        "landscape" to 0xE564, // 风景
        "language" to 0xE894, // 语言
        "laptop" to 0xE31E, // 笔记本
        "light_mode" to 0xE518, // 浅色模式
        "lightbulb" to 0xE90F, // 灯泡
        "local_airport" to 0xE53D, // 机场
        "local_bar" to 0xE540, // 酒吧
        "local_cafe" to 0xEB44, // 咖啡馆
        "local_dining" to 0xE561, // 用餐
        "local_drink" to 0xE544, // 饮料
        "local_gas_station" to 0xE546, // 加油站
        "local_hospital" to 0xE548, // 医院
        "local_laundry_service" to 0xE54A, // 洗衣服务
        "local_library" to 0xE54B, // 图书馆
        "local_mall" to 0xE54C, // 商场
        "local_offer" to 0xF05B, // 优惠
        "local_parking" to 0xE54F, // 停车
        "local_shipping" to 0xE558, // 货运
        "local_taxi" to 0xE559, // 出租车
        "location_on" to 0xF1DB, // 位置
        "lock" to 0xE899, // 锁
        "lunch_dining" to 0xEA61, // 午餐
        "magic_button" to 0xF136, // 魔法按钮
        "mail" to 0xE159, // 邮件
        "manage_accounts" to 0xF02E, // 账户管理
        "mark_email_read" to 0xF18C, // 邮件已读
        "masks" to 0xF218, // 口罩
        "medical_information" to 0xEBED, // 医疗信息
        "medical_services" to 0xF109, // 医疗服务
        "medication" to 0xF033, // 药物
        "meeting_room" to 0xEB4F, // 会议室
        "menu" to 0xE5D2, // 菜单
        "menu_book" to 0xEA19, // 菜单书
        "microwave" to 0xF204, // 微波炉
        "mode_fan" to 0xF168, // 风扇
        "model_training" to 0xF0CF, // 模型训练
        "modeling" to 0xF3AA, // 建模
        "money" to 0xE57D, // 钱币
        "mood" to 0xEA22, // 心情
        "mood_bad" to 0xE7F3, // 心情差
        "more_horiz" to 0xE5D3, // 更多
        "more_vert" to 0xE5D4,
        "motorcycle" to 0xE91B, // 摩托
        "move_to_inbox" to 0xE168, // 移至收件箱
        "movie" to 0xE404, // 电影
        "multicooker" to 0xE293, // 多功能锅
        "music_note" to 0xE405, // 音乐
        "nature" to 0xE406, // 自然
        "nature_people" to 0xE407, // 自然人物
        "network_cell" to 0xE1B9, // 蜂窝网络
        "network_wifi" to 0xE1BA, // WiFi
        "neurology" to 0xE10E, // 神经网络
        "nordic_walking" to 0xE50E, // 北欧步行
        "note_add" to 0xE89C, // 添加笔记
        "notifications" to 0xE7F5, // 通知
        "numbers" to 0xEAC7, // 数字
        "outbox" to 0xEF5F, // 发件箱
        "outdoor_grill" to 0xEA47, // 烧烤
        "oven" to 0xE9C7, // 烤箱
        "paid" to 0xF041, // 已付
        "palette" to 0xE40A, // 调色板
        "paragliding" to 0xE50F, // 滑翔伞
        "park" to 0xEA63, // 公园
        "payments" to 0xEF63, // 支付
        "people" to 0xEA21,
        "person" to 0xF0D3, // 个人
        "personal_injury" to 0xE6DA, // 人身伤害
        "pets" to 0xE91D, // 宠物
        "piano" to 0xE521, // 钢琴
        "pill" to 0xE11F, // 药丸
        "playground" to 0xF28E, // 游乐场
        "playground_2" to 0xF28F, // 游乐场2
        "pool" to 0xEB48, // 台球
        "post_add" to 0xEA20, // 添加帖子
        "power" to 0xE63C, // 电源
        "price_change" to 0xF04A, // 价格变动
        "price_check" to 0xF04B, // 价格核对
        "print" to 0xE8AD, // 打印
        "psychology" to 0xEA4A, // 心理
        "public" to 0xE80B, // 公共
        "publish" to 0xE255, // 发布
        "qr_code" to 0xEF6B, // 二维码
        "qr_code_scanner" to 0xF206, // 扫码
        "quiz" to 0xF04C, // 测验
        "ramen_dining" to 0xEA64, // 拉面
        "receipt" to 0xE8B0, // 收据
        "receipt_long" to 0xEF6E, // 长收据
        "redeem" to 0xE8F6, // 礼品
        "refresh" to 0xE5D5, // 刷新
        "request_quote" to 0xF1B6, // 报价请求
        "restaurant" to 0xE56C, // 餐厅
        "restaurant_menu" to 0xE561,
        "robot" to 0xF882, // 机器人
        "roller_skating" to 0xEBCD, // 轮滑
        "roofing" to 0xF201, // 屋顶
        "rowing" to 0xE921, // 划船
        "rv_hookup" to 0xE642, // 房车挂钩
        "sailing" to 0xE502, // 帆船
        "savings" to 0xE2EB, // 储蓄
        "schedule" to 0xEFD6, // 日程
        "school" to 0xE80C, // 学校
        "science" to 0xEA4B, // 科学
        "scuba_diving" to 0xEBCE, // 水肺潜水
        "sd_card" to 0xE623, // SD卡
        "search" to 0xE8B6, // 搜索
        "search_off" to 0xEA76, // 无搜索结果
        "security" to 0xE32A, // 安全
        "self_improvement" to 0xEA78, // 自我提升
        "sell" to 0xF05B, // 出售
        "send" to 0xE163, // 发送
        "sentiment_dissatisfied" to 0xE811, // 不满
        "sentiment_satisfied" to 0xE813, // 满意
        "set_meal" to 0xF1EA, // 套餐
        "settings" to 0xE8B8, // 设置
        "severe_cold" to 0xEBD3, // 重感冒
        "share" to 0xE80D, // 分享
        "shopping_bag" to 0xF1CC, // 购物袋
        "shopping_cart" to 0xE8CC, // 购物车
        "shoppingmode" to 0xEFB7, // 购物模式
        "show_chart" to 0xE6E1, // 折线图
        "sick" to 0xF220, // 生病
        "sim_card" to 0xE32B, // SIM卡
        "skateboarding" to 0xE511, // 滑板
        "smart_toy" to 0xF06C, // 智能助手
        "smartphone" to 0xE7BA, // 手机
        "snowboarding" to 0xE513, // 滑雪板
        "snowmobile" to 0xE503, // 雪地摩托
        "sort" to 0xE164, // 排序
        "sort_by_alpha" to 0xE053, // 按字母排序
        "soup_kitchen" to 0xE7D3, // 汤
        "spa" to 0xEB4C, // 水疗
        "speaker" to 0xE32D, // 音箱
        "sports_baseball" to 0xEA51, // 棒球
        "sports_basketball" to 0xEA26, // 篮球
        "sports_esports" to 0xEA28, // 电竞
        "sports_football" to 0xEA29, // 橄榄球
        "sports_golf" to 0xEA2A, // 高尔夫
        "sports_handball" to 0xEA33, // 手球
        "sports_hockey" to 0xEA2B, // 冰球
        "sports_mma" to 0xEA2C, // 格斗
        "sports_rugby" to 0xEA2E,
        "sports_soccer" to 0xEA2F, // 足球
        "sports_tennis" to 0xEA32, // 网球
        "sports_volleyball" to 0xEA31, // 排球
        "square_foot" to 0xEA49, // 平方英尺
        "star" to 0xF09A, // 星星
        "stethoscope" to 0xF805, // 听诊器
        "storage" to 0xE1DB, // 存储
        "store" to 0xE8D1, // 商店
        "storefront" to 0xEA12, // 店铺
        "subscriptions" to 0xE064, // 订阅
        "subway" to 0xE56F, // 地铁
        "sunny" to 0xE81A, // 晴天
        "support_agent" to 0xF0E2, // 客服
        "surfing" to 0xE515, // 冲浪
        "surgical" to 0xE131, // 外科
        "tablet" to 0xE32F, // 平板
        "takeout_dining" to 0xEA74, // 外卖
        "tapas" to 0xF1E9, // 小吃
        "taxi_alert" to 0xEF74, // 出租车警报
        "terrain" to 0xE564,
        "theater_comedy" to 0xEA66, // 喜剧
        "thermometer" to 0xE846, // 体温计
        "thermostat" to 0xF076, // 恒温器
        "thumb_down" to 0xF578, // 点踩
        "thumb_up" to 0xF577, // 点赞
        "thunderstorm" to 0xEBDB, // 雷暴
        "tire_repair" to 0xEBC8, // 轮胎维修
        "tornado" to 0xE199, // 龙卷风
        "toys" to 0xE332, // 玩具
        "traffic" to 0xE565, // 交通
        "train" to 0xE570, // 火车
        "tram" to 0xE571, // 电车
        "translate" to 0xE8E2, // 翻译
        "travel_explore" to 0xE2DB, // 旅行探索
        "trending_up" to 0xE8E5, // 上升趋势
        "tsunami" to 0xEBD8, // 海啸
        "tune" to 0xE429, // 调节
        "tv" to 0xE63B, // 电视
        "two_wheeler" to 0xE9F9, // 两轮车
        "unarchive" to 0xE169, // 恢复
        "upload" to 0xF09B, // 上传
        "usb" to 0xE1E0, // USB
        "vaccines" to 0xE138, // 疫苗
        "verified" to 0xEF76, // 已验证
        "videocam" to 0xE04B, // 摄像
        "volunteer_activism" to 0xEA70, // 志愿公益
        "wallet" to 0xF8FF, // 钱包
        "ward" to 0xE13C, // 病房
        "warehouse" to 0xEBB8, // 仓库
        "watch" to 0xE334, // 手表
        "water_drop" to 0xE798, // 水滴
        "waves" to 0xE176, // 波浪
        "wifi" to 0xE63E, // 无线网
        "wine_bar" to 0xF1E8, // 红酒
        "work" to 0xE943, // 工作
        "workspace_premium" to 0xE7AF, // 高级工作区
        "workspaces" to 0xEA0F, // 工作空间
        "yard" to 0xF089, // 庭院
    )

    fun get(name: String): Int = codepoints[name] ?: codepoints[FALLBACK] ?: 0xE5D4

    fun contains(name: String): Boolean = name in codepoints
}
