package com.agguy.moni.app.theme

import androidx.compose.ui.graphics.Color

val PrimaryLight = Color(0xFF006C4C)
val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFF88F8C8)
val OnPrimaryContainerLight = Color(0xFF002114)
val SecondaryLight = Color(0xFF4D6357)
val OnSecondaryLight = Color(0xFFFFFFFF)
val SecondaryContainerLight = Color(0xFFCFE9D9)
val OnSecondaryContainerLight = Color(0xFF092016)
val TertiaryLight = Color(0xFF3D6473)
val OnTertiaryLight = Color(0xFFFFFFFF)
val TertiaryContainerLight = Color(0xFFC1E8FB)
val OnTertiaryContainerLight = Color(0xFF001F29)
val ErrorLight = Color(0xFFBA1A1A)
val OnErrorLight = Color(0xFFFFFFFF)
val ErrorContainerLight = Color(0xFFFFDAD6)
val OnErrorContainerLight = Color(0xFF410002)
val BackgroundLight = Color(0xFFFBFDF8)
val OnBackgroundLight = Color(0xFF191C1A)
val SurfaceLight = Color(0xFFFBFDF8)
val OnSurfaceLight = Color(0xFF191C1A)
val SurfaceVariantLight = Color(0xFFDCE5DD)
val OnSurfaceVariantLight = Color(0xFF404943)
val OutlineLight = Color(0xFF707973)
val IncomeGreen = Color(0xFF00B894)
val ExpenseRed = Color(0xFFFF6B6B)
